info:
  app:
    environment: "PROD"

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true